import {
  Wifi,
  Wind,
  Tv,
  UtensilsCrossed,
  WashingMachine,
  Coffee,
  Car,
  Flame,
  Mountain,
  TreePalm,
  Eye,
  Plug,
  Cigarette,
  DoorOpen,
  Waves,
  Armchair,
  Bed,
  ShieldCheck,
  Droplets,
  ThermometerSun,
  Shirt,
  Sun,
  Dog,
  Book,
  Lock,
  Luggage,
  Bath,
  type LucideIcon,
} from 'lucide-react'
import { amenityLabels } from '@/lib/amenities'

const iconMap: Record<string, LucideIcon> = {
  wifi: Wifi,
  air_conditioning: Wind,
  air_conditioning_every_room: Wind,
  heating: ThermometerSun,
  hot_water: Droplets,
  bed_linens: Bed,
  towels: Bath,
  hangers: Shirt,
  wardrobe_closet: DoorOpen,
  extra_pillows_blankets: Bed,
  blackout_curtains: Eye,
  walk_in_shower: Waves,
  bathtub: Bath,
  hair_dryer: Wind,
  toiletries: Droplets,
  shampoo_conditioner: Droplets,
  body_soap: Droplets,
  fully_equipped_kitchen: UtensilsCrossed,
  kitchenette: UtensilsCrossed,
  refrigerator: UtensilsCrossed,
  stove: Flame,
  oven: UtensilsCrossed,
  microwave: UtensilsCrossed,
  dishwasher: UtensilsCrossed,
  coffee_machine: Coffee,
  coffee_machine_pods: Coffee,
  kettle: Coffee,
  toaster: UtensilsCrossed,
  cooking_basics: UtensilsCrossed,
  dishes_cutlery: UtensilsCrossed,
  tv: Tv,
  tv_every_room: Tv,
  smart_tv: Tv,
  netflix: Tv,
  streaming_services: Tv,
  satellite_tv: Tv,
  books_games: Book,
  washing_machine: WashingMachine,
  dryer: WashingMachine,
  clothes_rack: Shirt,
  iron_ironing_board: Shirt,
  work_desk: Armchair,
  safe: Lock,
  balcony: Eye,
  terrace: Armchair,
  garden: TreePalm,
  outdoor_furniture: Armchair,
  outdoor_seating: Armchair,
  outdoor_dining: UtensilsCrossed,
  bbq: Flame,
  sun_loungers: Sun,
  sea_view: Waves,
  mountain_view: Mountain,
  garden_view: TreePalm,
  hill_view: Mountain,
  city_view: Eye,
  free_parking: Car,
  street_parking: Car,
  ev_charging: Plug,
  self_checkin: DoorOpen,
  private_entrance: DoorOpen,
  luggage_storage: Luggage,
  smoke_alarm: ShieldCheck,
  fire_extinguisher: ShieldCheck,
  first_aid_kit: ShieldCheck,
  non_smoking: Cigarette,
  pet_friendly: Dog,
}

export function AmenityIcon({ amenity }: { amenity: string }) {
  const Icon = iconMap[amenity]
  const label = amenityLabels[amenity]
  if (!label) return null

  return (
    <div className="flex items-center gap-2 text-sm text-muted-foreground">
      {Icon ? <Icon className="h-4 w-4 shrink-0" /> : <span className="h-4 w-4" />}
      <span>{label}</span>
    </div>
  )
}
